// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entities

import (
	"time"

	"gorm.io/gorm"
)

const TableNameNulabBacklogIssue = "nulab_backlog_issue"

// NulabBacklogIssue mapped from table <nulab_backlog_issue>
type NulabBacklogIssue struct {
	ID        *string        `gorm:"column:id;type:uuid;primaryKey;default:uuid_generate_v4()" json:"id"`
	BacklogID *string        `gorm:"column:backlog_id;type:character varying(50)" json:"backlog_id"`
	GitID     *string        `gorm:"column:git_id;type:character varying(50)" json:"git_id"`
	CreatedAt *time.Time     `gorm:"column:created_at;type:timestamp without time zone;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt *time.Time     `gorm:"column:updated_at;type:timestamp without time zone" json:"updated_at"`
	DeletedAt gorm.DeletedAt `gorm:"column:deleted_at;type:timestamp without time zone" json:"deleted_at"`
}

// TableName NulabBacklogIssue's table name
func (*NulabBacklogIssue) TableName() string {
	return TableNameNulabBacklogIssue
}
